# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-12 12:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cm', '0002_remove_monitoring_kunde'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalArchiv',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('vm', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='cm.VM')),
            ],
            options={
                'verbose_name': 'historical archiv',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
        ),
        migrations.CreateModel(
            name='HistoricalBackup',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical backup',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
        ),
        migrations.CreateModel(
            name='HistoricalChange',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('nummer', models.PositiveSmallIntegerField()),
                ('ticketid', models.PositiveIntegerField(default='')),
                ('auftraggeber', models.CharField(default='', max_length=100)),
                ('change', models.TextField()),
                ('datum', models.DateTimeField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('techniker', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('vm', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='cm.VM')),
            ],
            options={
                'verbose_name': 'historical change',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
        ),
        migrations.CreateModel(
            name='HistoricalDisk',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('size', models.PositiveSmallIntegerField(default='')),
                ('prov', models.CharField(choices=[('Thin', 'Thin Provisioned'), ('Thick_LZ', 'Thick Lazy Zeroed'), ('Thick_EZ', 'Thick Eager Zeroed')], default='THIN', max_length=100)),
                ('location', models.CharField(choices=[('withVM', 'with VM'), ('separate', 'separate')], default='withVM', max_length=50)),
                ('node', models.CharField(choices=[('0:0', '0:0'), ('0:1', '0:1'), ('0:2', '0:2'), ('0:3', '0:3'), ('0:4', '0:4'), ('0:5', '0:5'), ('0:6', '0:6'), ('0:7', '0:7'), ('1:0', '1:0'), ('1:1', '1:1'), ('1:2', '1:2'), ('1:3', '1:3'), ('1:4', '1:4'), ('1:5', '1:5'), ('1:6', '1:6'), ('1:7', '1:7')], default='0:0', max_length=100)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('scsi', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='cm.SCSI')),
            ],
            options={
                'verbose_name': 'historical disk',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
        ),
        migrations.CreateModel(
            name='HistoricalKunde',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('strasse', models.CharField(max_length=200)),
                ('hausnummer', models.PositiveSmallIntegerField()),
                ('ort', models.CharField(max_length=200)),
                ('plz', models.PositiveSmallIntegerField()),
                ('ansprechpartner', models.CharField(default='', max_length=200)),
                ('telefon', models.CharField(default='', max_length=20)),
                ('email', models.EmailField(default='', max_length=200)),
                ('fax', models.CharField(default='', max_length=20)),
                ('mks', models.PositiveIntegerField(default='')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical kunde',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
        ),
        migrations.CreateModel(
            name='HistoricalMonitoring',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('vm', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='cm.VM')),
            ],
            options={
                'verbose_name': 'historical monitoring',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
        ),
        migrations.CreateModel(
            name='HistoricalNic',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('network', models.CharField(default='', max_length=100)),
                ('vlanid', models.PositiveSmallIntegerField(default='')),
                ('adapter', models.CharField(choices=[('vmxnet3', 'vmxnet3'), ('e1000', 'e1000'), ('e1000e', 'e1000e'), ('flexibel', 'flexibel')], default='vmxnet3', max_length=50)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('vm', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='cm.VM')),
            ],
            options={
                'verbose_name': 'historical nic',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
        ),
        migrations.CreateModel(
            name='HistoricalSCSI',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('adapter', models.CharField(choices=[('lsipar', 'LSI Logic Parallel'), ('lsisas', 'LSI Logic SAS'), ('pvscsi', 'Paravirtual SCSI')], default='pvscsi', max_length=50)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('vm', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='cm.VM')),
            ],
            options={
                'verbose_name': 'historical scsi',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
        ),
        migrations.CreateModel(
            name='HistoricalVM',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('creationdate', models.DateTimeField(default=django.utils.timezone.now)),
                ('beschreibung', models.CharField(default='', max_length=50)),
                ('inventory_location', models.CharField(default='', max_length=200)),
                ('datacenter_cluster', models.CharField(choices=[('PEG-RZ1+2', (('FKS', 'FKS'), ('NUE', 'NUE'))), ('PEG-RZ3', (('RST', 'RST'),)), ('PEG-RZ4', (('REG', 'REG'),))], default='NUE', max_length=3)),
                ('ressource_pool', models.CharField(default='', max_length=50)),
                ('storage', models.CharField(choices=[('NUE', (('NUE-A', 'NUE-Tier-A'), ('NUE-B', 'NUE-Tier-B'), ('NUE-C', 'NUE-Tier-C'))), ('FKS', (('FKS-A', 'FKS-Tier-A'), ('FKS-B', 'FKS-Tier-B'), ('FKS-C', 'FKS-Tier-C'))), ('RST', (('RST-A', 'RST-Tier-A'), ('RST-B', 'RST-Tier-B'), ('RST-C', 'RST-Tier-C'))), ('REG', (('REG-A', 'REG-Tier-A'), ('REG-B', 'REG-Tier-B'), ('REG-C', 'REG-Tier-C')))], default='', max_length=100)),
                ('vm_version', models.CharField(choices=[('VMX-08', 'VMX-08'), ('VMX-09', 'VMX-09'), ('VMX-10', 'VMX-10')], default='VMX-10', max_length=50)),
                ('os_version', models.CharField(choices=[('WIN2K8', 'Windows Server 2008'), ('WIN2K8R2', 'Windows Server 2008 R2'), ('WIN2K12', 'Windows Server 2012'), ('WIN2K12R2', 'Windows Server 2012 R2'), ('LX-DEB8', 'Debian Linux 8'), ('LX-RH', 'RedHat Linux'), ('OTHER', 'Anderes OS')], default='WIN2K12R2', max_length=100)),
                ('cpu', models.PositiveSmallIntegerField(choices=[(1, '1 vCPU  (1 socket,  1 core per socket)'), (2, '2 vCPUs (1 socket,  2 cores per socket)'), (4, '4 vCPUs (1 socket,  4 cores per socket)'), (8, '8 vCPUs (2 sockets, 4 cores per socket)')], default='1')),
                ('ram', models.PositiveSmallIntegerField(default=4)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical vm',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
        ),
        migrations.AlterField(
            model_name='kunde',
            name='mks',
            field=models.PositiveIntegerField(default=''),
        ),
        migrations.AddField(
            model_name='historicalvm',
            name='kunde',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='cm.Kunde'),
        ),
        migrations.AddField(
            model_name='historicalbackup',
            name='kunde',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='cm.Kunde'),
        ),
        migrations.AddField(
            model_name='historicalbackup',
            name='vm',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='cm.VM'),
        ),
    ]
