# Generated by Django 2.0.3 on 2018-04-15 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtbackup', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='mgt_ip',
            field=models.GenericIPAddressField(default='0.0.0.0', protocol='IPv4'),
        ),
        migrations.AlterField(
            model_name='device',
            name='password',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='device',
            name='username',
            field=models.CharField(default='admin', max_length=50),
        ),
    ]
