# Generated by Django 2.0.3 on 2018-03-26 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mtbackup', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Devices',
            new_name='Device',
        ),
    ]
