# Generated by Django 2.0.3 on 2018-04-15 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtbackup', '0002_auto_20180415_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='mgt_ip',
            field=models.GenericIPAddressField(protocol='IPv4'),
        ),
        migrations.AlterField(
            model_name='device',
            name='username',
            field=models.CharField(max_length=50),
        ),
    ]
