# Generated by Django 2.0.3 on 2018-03-28 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtbackup', '0002_auto_20180326_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='mgt_ip',
            field=models.GenericIPAddressField(protocol='IPv4'),
        ),
    ]
