# Generated by Django 2.0.3 on 2018-04-15 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtbackup', '0003_auto_20180415_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
