# Generated by Django 2.0.4 on 2018-04-05 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtbackup', '0004_auto_20180328_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='password',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
