# Generated by Django 2.0.3 on 2018-05-22 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_beat', '0006_auto_20180210_1226'),
        ('mtbackup', '0004_device_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cust_name', models.CharField(max_length=100)),
                ('cust_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('crontabschedule_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_celery_beat.CrontabSchedule')),
            ],
            bases=('django_celery_beat.crontabschedule',),
        ),
        migrations.AlterModelOptions(
            name='device',
            options={'ordering': ['hostname']},
        ),
        migrations.AddField(
            model_name='device',
            name='description',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='device',
            name='mgt_port',
            field=models.IntegerField(default=22),
        ),
    ]
