# Generated by Django 2.0.3 on 2018-05-22 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mtbackup', '0007_auto_20180522_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='customer',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='mtbackup.Customer'),
        ),
    ]
