# Generated by Django 2.0.3 on 2018-05-22 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mtbackup', '0008_device_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='comment',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='device',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mtbackup.Customer'),
        ),
    ]
