# Generated by Django 2.0.3 on 2018-05-28 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mtbackup', '0009_auto_20180522_2327'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['number']},
        ),
        migrations.RemoveField(
            model_name='device',
            name='slug',
        ),
    ]
